---
title: "python-intro-1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
knitr::knit_engines$set(python = reticulate::eng_python)
```

```{python}
# python as a calculator
3 + 5 * 4
```

```{python}
# assign a value to a variable
weight_kg = 60
```

Variable names:
- can include letters, digits, and underscores
- cannot start with a digit
- are case sensitive

## Types of Data
Common types:
- integer numbers
- floating point numbers
- strings

```{python}
# variable with a floating point value
weight_kg = 60.0
```

```{python}
weight_kg_text = 'weight in kilograms:'
```

```{python}
print(weight_kg)
```

```{python}
# display multiple things at once
print(weight_kg_text, weight_kg)
```

```{python}
# do arithmetic with variables right inside the print function
print('weight in pounds:', 2.2 * weight_kg)
# did not change the value of weight_kg
```

```{python}
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)
```

```{python}
# there are 2.2 pounds per kg
weight_lb = 2.2 * weight_kg
print(weight_kg_text, weight_kg, 'and in pounds:', weight_lb)
```

```{python}
weight_kg = 100.0
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)
# weight_lb doesn't "remember" where it got its value from
```

## Loading data into Python

```{python}
import numpy 
```

```{bash}
cd /home/guest/python-fun/swc-python/data
```


```{python}
# library(reticulate)
numpy.loadtxt(fname='/home/guest/python-fun/swc-python/data/inflammation-01.csv', delimiter=',')
```

```{python}

```

```{python}

```

```{python}

```


